package main.java.View;

import java.util.regex.Pattern;

public class Response {
    public static String loginFirst = "please login first";
    public static String menuNotPossible = "menu navigation is not possible";
    public static String userCreateSuccessfully = "user created successfully!";
    public static String userLoginSuccessfully = "user logged in successfully!";
    public static String wrongUsernameOrPassword = "Username and password didn’t match!";
    public static String userLogoutSuccessfully = "user logged out successfully!";
    public static String changeNicknameSuccessfully = "nickname changed successfully!";
    public static String changePasswordSuccessfully = "password changed successfully!";
    public static String invalidCurrentPassword = "current password is invalid";
    public static String samePasswordError = "please enter a new password";
    public static String deckCreateSuccessfully = "deck created successfully!";
    public static String deckDeleteSuccessfully = "deck deleted successfully";
    public static String deckActiveSuccessfully = "deck activated successfully";
    public static String addCardSuccessfully = "card added to deck successfully";
    public static String removeCardSuccessfully = "card removed form deck successfully";
    public static String cardNameNotExist = "there is no card with this name";
    public static String notEnoughMoney = "not enough money";
    public static String usernameNotExist = "there is no player with this username";
    public static String invalidRoundNumber = "number of rounds is not supported";
    public static String invalidSelection = "invalid selection";
    public static String cardSelected = "card selected";
    public static String notFoundCardinPosition = "no card found in the given position";
    public static String notCardSelected = "no card is selected yet";
    public static String cardDeselected = "card deselected";
    public static String cantSummon = "you can’t summon this card";
    public static String actionNotAllowed = "action not allowed in this phase";
    public static String monsterCardZoneFull = "monster card zone is full";
    public static String alreadySummonedOrSet = "you already summoned/set on this turn";
    public static String summonedSuccessfully = "summoned successfully";
    public static String notEnoughCardForTribute = "there are not enough cards for tribute";
    public static String noMonsterOnThisAddress = "there no monsters on this address";
    public static String noMonsterOnOneOfAddress = "there no monsters on one of this addresses";
    public static String cantSetThisCard = "you can’t set this card";
    public static String cantDoActionInThisPhase = "you can’t do this action in this phase";
    public static String setSuccessfully = "set successfully";
    public static String cantChangeCardPosition = "you can’t change this card position";
    public static String alreadyInWantedPosition = "this card is already in the wanted position";
    public static String alreadyChangedPosition = "you already changed this card position in this turn";
    public static String monsterCardPositionChangedSuccessfully = "monster card position changed successfully";
    public static String cantFlipSummonCard = "you can’t flip summon this card";
    public static String flipSummonCardSuccessfully = "flip summoned successfully";
    public static String cantAttackWithThisCard = "you can’t attack with this card";
    public static String alreadyAttacked = "this card already attacked";
    public static String noCardToAttack = "there is no card to attack here";
    public static String bothMonsterCardDestroyed = "both you and your opponent monster cards are destroyed and no\n" +
            "one receives damage";
    public static String defencePositionMonsterDestroyed = "the defense position monster is destroyed";
    public static String noCardDestroyed = "no card is destroyed";
    public static String activeEffectErrorForSpellCard = "activate effect is only for spell cards.";
    public static String cantActiveEffect = "you can’t activate an effect on this turn";
    public static String alreadyActive = "you have already activated this card";
    public static String notDonePreparationsOfSpell = "preparations of this spell are not done yet";
    public static String spellActivated = "spell activated";
    public static String activeTrapAndSpellQuestion = "do you want to activate your trap and spell?";
    public static String notTurnToMove = "it’s not your turn to play this kind of moves";
    public static String spellOrTrapActivated = "spell/trap activated";
    public static String noWayCouldRitualSummonMonster = "there is no way you could ritual summon a monster";
    public static String shouldRitualSummon = "you should ritual summon right now";
    public static String dontMatchLevels = "selected monsters levels don’t match with ritual monster";
    public static String noWayCouldSpecialSummonMonster = "there is no way you could special summon a monster";
    public static String shouldSpecialSummon = "you should special summon right now";
    public static String graveyardEmpty = "graveyard empty";
    public static String cardNotVisible = "card is not visible";
    public static String activeDeckNotAvailable = "has no active deck";
    public static String invalidDeck=" deck is invalid";
}
